export type Language = "en" | "zh-CN";

// UI copy only. Never pass memory content, model output, or external identifiers here.
export const chineseCopy: Record<string, string> = {
  "Memory Library": "记忆管理",
  "Memory Migration & Privacy": "记忆迁移与隐私保护",
  "Open Memory Library": "打开记忆管理",
  "Import, preview, edit and export structured memories without asking a question.": "无需提问，即可导入、预览、编辑和导出结构化记忆。",
  "Persist governance changes with conflict checks and backups; hidden or deleted memories leave retrieval.": "治理操作持久保存，并提供冲突检查和备份；隐藏或删除的记忆不再被召回。",
  "Switch interface language and inspect credential-redaction markers without rewriting your memories.": "中英文界面与明确的凭据遮蔽标记，不会改写你的原始记忆。",
  "Your local memory library, your decisions. Inspect and migrate records, then see how governance changes retrieval.": "你的本地记忆库，由你决定。查看与迁移记录，再观察治理如何改变检索。",
  "Know the boundaries": "了解能力边界",
  "Pensieve manages its own local library, not your host application's private memory. The heatmap is simulated, not model attention.": "Pensieve 管理自己的本地记忆库，不会自动修改宿主的私有记忆。热力图是模拟结果，不代表模型内部注意力。",
  "[REDACTED:...] marks detected credentials in generated text. Raw memories and backups remain original data; review before sharing.": "[REDACTED:...] 标记生成文本中检测到的凭据。原始记忆与备份保留原文，分享前请检查。",
  "Read the guide": "阅读使用指南",
  ": import, review, edit and export without a query.": "：无需提问即可导入、检查、编辑和导出。",
  "Home": "首页", "Guide": "使用指南", "User View": "用户视图", "Surface Model": "模型视图",
  "Generic Host": "通用宿主", "verified": "已验证", "drifted": "状态不一致", "missing": "缺失",
  "preference": "偏好", "behavioral": "行为", "financial": "财务", "medical": "医疗", "identity": "身份",
  "mock": "模拟", "live": "在线", "fallback": "本地回退",
  "overview": "概览", "inspection": "检查",
  "Invalid origin / 来源无效": "来源无效", "Invalid query / 查询无效": "查询无效",
  "Live request failed; showing local simulation / 在线请求失败，已显示本地模拟": "在线请求失败，已显示本地模拟",
  "Memories changed; retry / 记忆已变化，请重试": "记忆已变化，请重试",
  "Cannot query memory store / 无法查询记忆库": "无法查询记忆库",
  "Cannot read memories / 无法读取记忆": "无法读取记忆",
  "Request failed / 请求失败": "请求失败", "Save failed / 保存失败": "保存失败",
  "A host-neutral dashboard shell for validating the plugin core outside a specific assistant surface.": "在不依赖特定助手的界面中验证插件内核。",
  "Optimized for local Codex sidebar embedding with provider injection and path review.": "面向本地 Codex 侧边栏，支持数据源注入与路径查看。",
  "Prepared for Claude Code-style local plugin hosting with the same structured memory contract.": "为 Claude Code 风格的本地插件宿主准备，采用相同的结构化记忆接口。",
  "Dashboard memory request failed.": "仪表盘记忆请求失败。", "Dashboard memory response did not include data.": "仪表盘响应缺少数据。", "Governance bridge request failed.": "治理桥接请求失败。", "Governance status response was incomplete.": "治理状态响应不完整。", "Governance report response was incomplete.": "治理报告响应不完整。", "Governance receipt response was incomplete.": "治理回执响应不完整。",
  "How to read Pensieve": "如何理解 Pensieve",
  "The current system combines a query-based memory-RAG interaction surface with a governance-aware memory portrait. The heatmap and activation logic are retrieval-facing; the dashboard and actions are user-facing.": "系统将基于提问的记忆检索与可治理的记忆画像结合起来。热力图与激活逻辑用于观察检索，仪表盘与操作控件用于管理记忆。",
  "Current Boundaries": "当前能力边界",
  "The current heatmap and activation surface are deterministic local simulations layered on top of memory-RAG retrieval.": "当前热力图与激活表层是记忆检索之上的确定性本地模拟，并非模型内部注意力。",
  "Live mode swaps the response narrative for a server-side OpenAI call, but keeps retrieval, ranking, and governance on the local product side.": "在线模式通过服务端调用 OpenAI 生成回答；检索、排序与治理仍由本地产品处理。",
  "Memory Library and the dashboard also work without a query. Changes affect Pensieve's local repository, not the host application's own memory.": "记忆库与仪表盘无需提问也可使用。操作影响 Pensieve 的本地记忆库，不会同步修改宿主应用自己的记忆。",
  "Submit a query to render token-to-memory influence.": "提交问题后，即可查看词语与记忆之间的模拟影响。",
  "Model View": "模型视图", "Influence Heatmap": "影响热力图", "Columns: input tokens": "列：输入词语", "Rows: memory units": "行：记忆单元",
  "v0.2 update": "v0.2 更新",
  "Observe how memory shapes an answer, then govern what remains prominent.": "看见记忆如何影响回答，决定哪些记忆应被保留与重视。",
  "Pensieve makes structured memory visible, explainable, and manageable. Explore query-based retrieval, or open Memory Library to review and migrate memories without asking a question.": "Pensieve 让结构化记忆可见、可解释、可管理。你可以通过提问观察检索，也可以直接打开记忆库查看、管理和迁移记忆。",
  "Open Surface Model": "打开模型表层", "Open User View": "打开用户视图", "Version Update": "版本更新", "What changed in this build": "本次更新内容",
  "This release pushes Pensieve further beyond demo mode and makes the query-based memory observability flow feel more coherent, reusable, and ready for hands-on testing.": "本次更新完善了记忆观察流程，让提问、解释与治理更加连贯，也便于复用与实际验证。",
  "Shared priority portrait across the routed app and the dashboard/plugin route.": "应用页面、仪表盘与插件共享一致的记忆优先级画像。",
  "Live request trace with submit time, settle time, response source, latency, and stale-response protection.": "请求追踪展示提交与完成时间、响应来源和耗时，并防止过期响应覆盖当前结果。",
  "Shared memory-item presenter so cards and ranked lists now describe memory state more consistently.": "卡片与排序列表采用统一的记忆展示方式，状态描述更加一致。",
  "Current System Read": "当前系统概览", "What the session currently emphasizes": "当前会话关注的记忆", "Last answer preview:": "上次回答预览：", "Page Roles": "页面分工",
  ": product overview and session status.": "：产品概览与会话状态。", ": mental model for memory, retrieval, and governance.": "：理解记忆、检索与治理。",
  ": memory portrait and human-readable priority.": "：记忆画像与可读的优先级。", ": query, answer, activation list, and heatmap.": "：提问、回答、激活列表与热力图。",
  "What Pensieve is": "Pensieve 是什么",
  "Pensieve is a memory observability and governance layer. It helps users inspect what structured memory the system holds, why it matters, and how lightweight actions may change future retrieval.": "Pensieve 是记忆的可观测与治理层，帮助用户了解系统保存了什么、这些记忆为何重要，以及管理操作如何影响未来检索。",
  "What a memory unit means": "什么是记忆单元",
  "A memory unit is a structured semantic record. It carries content, keywords, relevance, risk, timestamps, activation counts, and governance state rather than being treated as an opaque block of text.": "记忆单元是一条结构化语义记录，包含内容、关键词、相关度、风险、时间、激活次数与治理状态，而非一段不可解释的文本。",
  "How relevance is computed": "相关度如何计算",
  "In the current query-based mode, the app tokenizes the query, retrieves from the memory-RAG store, reranks by similarity plus governance modifiers, and then surfaces the highest-weight memories.": "提问模式会拆分输入，从记忆库检索，结合相似度与治理状态重新排序，再展示权重最高的记忆。",
  "What governance actions mean": "治理操作的含义",
  "Pin raises prominence, soften lowers prominence, hide suppresses active retrieval without destructive deletion, restore returns a hidden memory to the visible field, and undo reverts the latest local action.": "置顶提高优先级，弱化降低优先级，隐藏阻止召回但不删除记录，恢复让隐藏记忆重新可见，撤销则回退最近一次可撤销操作。",
  "Query": "问题", "Pinned": "已置顶", "pinned": "已置顶", "Context Drift": "上下文漂移", "CDV Violation": "上下文违规", "CDV Clean": "上下文正常",
  "Influence": "影响程度", "Why It Surfaced": "为何被召回", "Context Drift Analysis": "上下文漂移分析", "Last Activated": "最近激活", "Activation Count": "激活次数",
  "Hide": "隐藏", "Restore": "恢复", "Pin": "置顶", "Unpin": "取消置顶", "Soften": "弱化", "Unsoften": "取消弱化",
  "Priority Portrait": "优先级画像", "Priority Keywords": "优先关键词", "Surfaced Themes": "浮现主题", "memories": "条记忆", "activations": "次激活", "visible memories": "条可见记忆",
  "Priority keywords will appear after the memory field becomes active.": "记忆被激活后，优先关键词将在这里显示。",
  "Themes will emerge when visible memories remain in the active field.": "存在可见记忆时，这里将展示相关主题。",
  "Weighted keywords and surfaced themes distilled from the current memory field.": "从当前记忆中提取的加权关键词与主题。",
  "Current memory hierarchy": "当前记忆优先级", "A compact portrait of which memory fragments, themes, and state buckets currently dominate the field.": "概览当前重要的记忆片段、主题与状态分布。",
  "Current activation hierarchy": "当前激活优先级", "The same retrieval pass produces both the observability surface and the human-readable priority portrait.": "同一次检索同时生成可观测表层与可读的优先级画像。",
  "Surface Memory": "唤起记忆", "Query-based memory observability": "基于提问的记忆观察",
  "Submit a query to trigger retrieval, reranking, explanation, and token-level influence in one coherent flow.": "提交问题，连续观察检索、重排序、解释与词语级模拟影响。",
  "Last submit:": "上次提交：", "Last settle:": "上次完成：", "Source:": "来源：", "Request Trace": "请求追踪", "How the latest submission moved through the system": "最近一次请求的处理过程",
  "Reset View": "重置视图", "Restore Hidden": "恢复隐藏记忆", "Undo": "撤销", "Response Layer": "响应层", "Answer and memory summary": "回答与记忆摘要", "Memory Summary": "记忆摘要",
  "Activated Field": "激活记忆", "Which memories are currently in play": "当前参与检索的记忆", "Memory Detail": "记忆详情", "Detailed activated memories": "激活记忆明细",
  "Current memory portrait": "当前记忆画像", "This page compresses the memory field into a human-readable priority portrait: top keywords, surfaced themes, state buckets, and the memory units most likely to influence the current response.": "通过关键词、主题、状态分布与记忆单元，清楚了解当前记忆的优先级。",
  "Memory Units": "记忆单元", "What the model currently remembers most": "当前优先记忆",
  "No visible memories remain. Restore hidden memories or submit a new query to repopulate the field.": "当前没有可见记忆。请恢复隐藏记忆，或在记忆库中导入记录。",
  "No strong memory match is active right now. The field is visible, but nothing is especially dominant for the current query.": "当前问题尚未激活明显相关的记忆。你仍可以查看现有记忆。",
  "This memory stayed available in the current field.": "这条记忆在当前记忆集中保持可用。", "This trace remained active.": "这条记忆仍处于激活状态。",
  "No strong memory match surfaced for the current query.": "未找到与当前问题高度相关的记忆。", "The field is currently dormant. Submit a query to activate retrieval.": "当前尚未启动检索。提交问题即可唤起记忆。",
  "Mock Host": "模拟宿主", "Sidebar adapter preview": "侧边栏适配器预览",
  "This local host simulates sidebar visibility, expansion, workspace context, and event capture without coupling Pensieve to any specific runtime.": "本地模拟侧边栏显示、展开、工作区上下文与事件捕获，不绑定特定宿主运行时。",
  "Rotate Workspace": "切换模拟工作区", "Clear Event Log": "清空事件日志", "Refresh Event Count": "刷新事件计数",
  "Host": "宿主", "Booting mock sidebar": "启动模拟侧边栏", "Initializing host context, sidebar state, and event bridge.": "正在初始化宿主上下文、侧边栏状态与事件桥接。",
  "Host Error": "宿主错误", "Adapter startup failed": "适配器启动失败", "Host Hidden": "宿主已隐藏", "Sidebar collapsed by host": "侧边栏已被宿主收起",
  "The dashboard remains mounted, but the host has marked the sidebar as not currently visible.": "仪表盘仍在运行，但宿主已将侧边栏设为不可见。",
  "Memory Dashboard": "记忆仪表盘", "A quiet local panel for inspecting what the system continues to hold in view.": "在轻量本地面板中，查看系统持续保留的记忆。",
  "Query-free": "无需提问", "Local provider": "本地数据源", "Structured memory": "结构化记忆", "mode": "模式", "Loading": "加载中", "Drawing the current memory field.": "正在读取当前记忆。", "Error": "错误",
  "Governance Bridge": "治理桥接", "Carry user decisions back to memory": "将治理决策写回记忆",
  "Compile the current governed state into a reviewable Markdown report and a deterministic host manifest.": "将当前治理状态整理为可审阅的 Markdown 报告与确定性宿主清单。",
  "Apply & verify": "应用并验证", "changes": "项变更", "Receipt:": "回执：", "checked": "项已检查",
  "Governance changes will appear here after you pin, soften, hide, or restore a memory.": "置顶、弱化、隐藏或恢复记忆后，治理变更将在这里显示。",
  "Priority": "优先级", "What the system holds prominent": "系统重点保留的记忆",
  "No priority keywords are currently visible in the active memory field.": "当前可见记忆中暂无优先关键词。", "No surfaced themes are available until more visible memories remain in the field.": "暂无主题；需要更多可见记忆。",
  "Memory List": "记忆列表", "entries": "条记录", "Empty field": "暂无记忆",
  "No visible memories are currently active. Restore hidden traces or wait for new memory input from the host.": "当前没有可见的活跃记忆。请恢复隐藏记录，或在记忆库中导入。",
  "Showing a": "当前展示", "based on risk, origin, and memory type.": "，由风险、来源与记忆类型决定。", "Activated": "激活时间", "Count": "次数", "Type": "类型", "Source": "来源", "Actions": "操作", "Confirm Hide": "确认隐藏", "Cancel": "取消",
  "Snapshot": "状态快照", "Memory field": "记忆概览", "Updated": "更新于",
  "The local repository is empty. Pensieve will surface a memory field once records are seeded by the provider.": "本地记忆库为空。通过记忆库导入记录后，即可在这里查看。",
  "Select a memory to inspect its trace and controls.": "选择一条记忆，查看来源与管理操作。", "Memory Inspector": "记忆检查器", "Trace, storage path, and lightweight controls": "来源追踪、存储路径与轻量管理",
  "This panel reflects the structured memory layer built from captured events, not direct parameter memory inside the model.": "此面板展示结构化记忆层，而非模型参数内部的记忆。",
  "Status:": "状态：", "Pinned:": "置顶：", "Storage path:": "存储路径：", "Last activated:": "最近激活：", "Info type:": "信息类型：", "Origin context:": "来源上下文：", "Trace": "来源追踪", "Source event ids:": "来源事件 ID：", "Source paths:": "来源路径：", "Extraction note:": "提取说明：",
  "Structured memories available for review": "可供查看的结构化记忆", "Select a memory to inspect its path, trace, metadata, and light governance controls.": "选择记忆以查看路径、来源、元数据与治理操作。",
  "Importance:": "重要度：", "Activations:": "激活次数：", "Store:": "存储：", "Loading the local memory field...": "正在加载本地记忆…", "Structured Memory Layer": "结构化记忆层", "Pensieve Plugin Core": "Pensieve 插件内核",
  "This dashboard exposes structured memory distilled from captured events, along with the local paths where those memories and vector artifacts live.": "此仪表盘展示结构化记忆及其本地存储路径；未配置的存储位置会明确标注。",
  "Provider": "数据提供方", "What the memory field weights most": "记忆集中的重点关键词", "Weighted from visible structured memories rather than direct LLM parameter state.": "权重来自可见的结构化记忆，而非大模型内部参数。",
  "No visible keyword priorities yet.": "暂无可见的优先关键词。", "How those memories cluster conceptually": "记忆中的相关主题", "Themes are derived locally from structured memory content and keywords.": "主题由本地记忆内容与关键词推导。", "Weighted signal:": "加权值：", "No visible themes yet.": "暂无可见主题。",
  "Host-Agnostic Plugin Core": "宿主无关的插件内核", "Structured memory dashboard for reviewing captured-memory artifacts and lightly governing their state.": "查看结构化记忆记录，并对其状态进行轻量治理。", "Hydrating local memory artifacts...": "正在读取本地记忆记录…",
  "Inspector": "检查器", "Expand the sidebar to review storage paths, source traces, and lightweight governance actions.": "展开侧边栏，查看存储路径、来源追踪与治理操作。", "Expand Inspector": "展开检查器",
  "A lightweight local plugin panel for inspecting structured LLM memory and gently adjusting what stays prominent.": "轻量本地插件面板，用于查看结构化记忆并调整其优先级。",
  "Mode": "模式", "Mock": "模拟", "Live": "在线", "MOCK": "模拟", "LIVE": "在线", "FALLBACK": "本地回退", "LOCAL": "本地", "Mock Mode": "模拟模式", "Live Mode": "在线模式",
  "Visible Memories": "可见记忆", "Pinned / Softened": "置顶 / 弱化", "Hidden": "已隐藏", "Active": "活跃", "Softened": "已弱化", "Total": "总计", "High Risk": "高风险",
  "active": "活跃", "softened": "已弱化", "hidden": "已隐藏", "forgotten": "已隐藏", "low": "低风险", "medium": "中风险", "high": "高风险", "low risk": "低风险", "medium risk": "中风险", "high risk": "高风险",
  "Ask something...": "输入你的问题…", "Consulting the basin...": "正在唤起记忆…", "Narrative Source": "回答来源", "Model": "模型",
  "Surfacing the current memory field and waiting for the response layer to settle.": "正在检索记忆，等待回答完成。", "The draft changed. Submit to refresh the answer, summary, and activation surface together.": "问题草稿已更改。提交后将同步更新回答、摘要与激活表层。",
  "The current answer, memory summary, and activation map are aligned to the last submitted query.": "当前回答、记忆摘要与激活图对应最近一次提交的问题。", "Ask a question to watch memory retrieval, reranking, and governance state come into view.": "提出问题，观察记忆检索、重排序与治理状态。",
  "none": "无", "None": "无", "pending": "等待中", "Pending": "等待中", "not-yet": "尚无", "Not yet": "尚无", "Request in flight": "请求处理中", "Session settled": "会话已完成", "Settled with local fallback": "已完成（本地回退）", "Settled": "已完成", "Idle": "空闲", "Waiting": "等待中",
  "Submitted Query": "已提交问题", "Requested Mode": "请求模式", "Response Source": "响应来源", "Submitted": "提交时间", "Latency": "耗时", "No query submitted in this session yet.": "本次会话尚未提交问题。",
  "Capture limit reached": "已达捕获上限", "Capturing": "捕获中", "Hide Sidebar": "隐藏侧边栏", "Show Sidebar": "显示侧边栏", "Compact Host": "收起宿主面板", "Expand Host": "展开宿主面板", "Collapse": "收起", "Expand": "展开", "compact": "紧凑", "expanded": "展开",
  "Failed to boot the host adapter.": "宿主适配器启动失败。", "Host context was not available.": "宿主上下文不可用。", "Verified": "已验证", "In sync": "已同步", "Working...": "处理中…", "Generate report": "生成报告", "Latest governance report is ready for provider synchronization.": "最新治理报告已就绪，可与数据源同步。",
  "Structured fragments and controls": "结构化片段与管理", "Top memory fragments": "优先记忆片段", "Inspect fragment detail, recency, and direct governance controls.": "查看片段详情、最近激活时间与治理操作。", "A ranked overview of the fragments currently staying most present.": "按优先级概览当前重要的记忆片段。",
  "Strong confirm": "敏感操作确认", "Confirm": "确认", "Full view": "完整视图", "Soft mask": "部分遮蔽", "Protected view": "受保护视图", "full view": "完整视图", "soft mask": "部分遮蔽", "protected view": "受保护视图",
  "General": "通用", "Preference": "偏好", "Behavioral": "行为", "Financial": "财务", "Medical": "医疗", "Identity": "身份", "Public": "公开", "Consent Required": "需要同意", "Confidentiality": "保密", "Reciprocity": "互惠", "Protected": "受保护", "Sensitive": "敏感",
  "Dashboard": "仪表盘", "Memories": "记忆", "Searchable": "可检索", "Selected": "已选择", "Sidebar-ready": "支持侧边栏", "Windowed": "独立窗口", "Provider injection": "支持注入数据源", "Manual provider": "手动数据源", "Local paths visible": "显示本地路径", "Paths abstracted": "路径已抽象",
  "yes": "是", "no": "否", "not yet activated": "尚未激活", "unspecified": "未指定", "Memory Store": "记忆存储", "Capture Store": "采集存储", "Vector Store": "向量存储", "Not yet mapped": "尚未配置",
  "Failed to load plugin dashboard.": "插件仪表盘加载失败。", "Failed to load memory trace.": "记忆来源加载失败。", "Failed to apply memory action.": "记忆操作失败。", "Failed to read governance status.": "读取治理状态失败。", "Failed to load the memory dashboard.": "记忆仪表盘加载失败。", "Refresh failed": "刷新失败", "Action failed.": "操作失败。", "Failed to generate governance report.": "生成治理报告失败。", "Failed to apply governance report.": "应用治理报告失败。"
};

export function translateUI(language: Language, text: string): string {
  return language === "zh-CN" && Object.hasOwn(chineseCopy, text) ? chineseCopy[text] : text;
}

export function localizeRelativeTime(language: Language, label?: string): string {
  if (!label) return translateUI(language, "Not yet");
  if (language === "en") return label;
  const match = /^(\d+)(h|d) ago$/.exec(label);
  return match ? `${match[1]} ${match[2] === "h" ? "小时前" : "天前"}` : label;
}
